apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-image-renderer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-image-renderer
  name: grafana-image-renderer
spec:
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
        kubernetes.io/hostname: __GrafanaNodeSelector__  
      containers:
        - name: grafana-image-renderer
          image: __ContainerRegistryAdminUser__.azurecr.io/ncs.grafana.renderer:__DFCGrafanaImageTag__
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLE_METRICS
              value: "true"
            - name: HTTP_PORT
              value: "8081"
            - name: HTTP_HOST
              value: "10.2.5.69"
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP           
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 500m
              memory: 2G
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-image-renderer-pv
      volumes:
        - name: grafana-image-renderer-pv
          persistentVolumeClaim:
            claimName: grafana-image-renderer-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: grafana-image-renderer
  type: ClusterIP
  sessionAffinity: None