parameters:
  ArmTemplateRoot: ''
  SolutionBaseName: ''

jobs:
- job: TestAndPublishArmTemplates
  displayName: Test and Publish Arm Templates
  pool: 'NCS - CI and CD'
  workspace:
    clean: all
  steps:
  - task: GitVersion@5
    inputs:
      preferBundledVersion: false
      updateAssemblyInfo: true
      configFilePath: './GitVersion.yml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: ${{ parameters.ArmTemplateRoot }}
      SolutionBaseName: ${{ parameters.SolutionBaseName }}
      PublishPipelineArtifact: true