parameters:
  DevSitContainerRegistryAdminUser: ''
  DevSitContainerRegistryPassword: ''
  PrdContainerRegistryAdminUser: ''
  PrdContainerRegistryPassword: ''
  DockerfileContext: ''
  DockerfileName: ''
  RenderDockerfileName: ''
  ImageBaseName: ''
  RenderImageBaseName: ''
  ImageTag: ''

jobs:
- job: BuildNCSGrafanaImage
  displayName: Build and publish NCS.Grafana.Image container
  pool: 'NCS - CI and CD'
  workspace:
    clean: all
  steps:
  - checkout: self
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: '${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'Resources/Dockerfiles/grafana.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.DevSitContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.DevSitContainerRegistryPassword }}
      DockerfileContext: '${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.RenderDockerfileName }}
      ImageBaseName: ${{ parameters.RenderImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'Resources/Dockerfiles/grafana-renderer.yaml'
# Below Images are for Pre-Prod and Prod Env's, This needs refactoring
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: '${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.DockerfileName }}
      ImageBaseName: ${{ parameters.ImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'Resources/Dockerfiles/grafana.yaml'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.PrdContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.PrdContainerRegistryPassword }}
      DockerfileContext: '${{ parameters.DockerfileContext }}'
      DockerfileName: ${{ parameters.RenderDockerfileName }}
      ImageBaseName: ${{ parameters.RenderImageBaseName }}
      ImageTag: ${{ parameters.ImageTag }}
      ManifestFilePath: 'Resources/Dockerfiles/grafana-renderer.yaml'
