parameters:
  ArmTemplateRoot: ''
  SolutionBaseName: ''

jobs:
- job: TestAndPublishArmTemplates
  displayName: Test and Publish Arm Templates
  pool: 'NCS - CI and CD'
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    inputs:
      preferBundledVersion: false
      updateAssemblyInfo: true
      useConfigFile: true
      versionSpec: '5.3.x'
      configFilePath: '$(Build.SourcesDirectory)\Resources\AzureDevOps\GitVersion.yml'
  - script: echo %Action%%BuildVersion%
    displayName: 'Set Build Number to Semantic Version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: '$(GitVersion.SemVer)'
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: ${{ parameters.ArmTemplateRoot }}
      SolutionBaseName: ${{ parameters.SolutionBaseName }}
      PublishPipelineArtifact: true