variables:
- name: DFCGrafanaImageTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: LAB
- name: ResourceGroup
  value: dfc-lab-stax-database-rg
- name: grafana-namespace
  value: grafana-lab