variables:
- name: DFCGrafanaImageTag
  value: $(Build.BuildNumber)
- name: ReleaseEnvironmentName
  value: PRD
- name: ResourceGroup
  value: dfc-prd-stax-database-rg
- name: grafana-namespace
  value: grafana-prd
- name: grafanarenderer-namespace
  value: grafana-imagerenderer